name: Builder

on:
  push:
    branches:
      - main

jobs:
  generate_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Python script
        run: |
          python builder/builder.py
        env:
          PYTHON_VERSION: 3.x # Specify the desired Python version here

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          current_date=$(date +"%Y-%m-%d")
          git add .
          git commit -m "Builder running at $current_date"
          git push
